#!/usr/bin/env python3 
from collections import OrderedDict

ptype="type"
pname="name"

syscalls = OrderedDict(
	{
		"read":                [{ptype: "int", pname: "fd"}, {ptype: "void*", pname: "buf"}, {ptype: "size_t", pname: "count"}, {ptype: "const char*", pname: "pathname"}],
		"write":               [{ptype: "int", pname: "fd"}, {ptype: "void*", pname: "buf"}, {ptype: "size_t", pname: "count"}, {ptype: "const char*", pname: "pathname"}],
		"open":                [{ptype: "const char*", pname: "pathname"}, {ptype: "int", pname: "flags"}, {ptype: "mode_t", pname: "mode"}],
		"close":               [{ptype: "int", pname: "fd"}, {ptype: "const char*", pname: "pathname"}],
		"stat":                [{ptype: "const char*", pname: "pathname"}, {ptype: "struct stat*", pname: "statbuf"}],
		"fstat":               [{ptype: "int", pname: "fd"}, {ptype: "struct stat*", pname: "statbuf"}, {ptype: "const char*", pname: "pathname"}],
		"lstat":               [{ptype: "const char*", pname: "pathname"}, {ptype: "struct stat*", pname: "statbuf"}],
		"poll":                [{ptype: "struct pollfd*", pname: "fds"}, {ptype: "unsigned int", pname: "nfds"}, {ptype: "int", pname: "timeout"}],
		"lseek":               [{ptype: "int", pname: "fd"}, {ptype: "off_t", pname: "offset"}, {ptype: "unsigned int", pname: "whence"}, {ptype: "const char*", pname: "pathname"}],
		"mmap":                [{ptype: "void*", pname: "addr"}, {ptype: "size_t", pname: "length"}, {ptype: "int", pname: "prot"}, {ptype: "int", pname: "flags"}, {ptype: "int", pname: "fd"}, {ptype: "off_t", pname: "off"}, {ptype: "const char*", pname: "pathname"}],
		"mprotect":            [{ptype: "void*", pname: "addr"}, {ptype: "size_t", pname: "len"}, {ptype: "int", pname: "prot"}],
		"munmap":              [{ptype: "void*", pname: "addr"}, {ptype: "size_t", pname: "length"}],
		"brk":                 [{ptype: "void*", pname: "addr"}],
		"rt_sigaction":         [{ptype: "int", pname: "signum"}, {ptype: "const struct sigaction*", pname: "act"}, {ptype: "struct sigaction*", pname: "oldact"}, {ptype: "size_t", pname: "sigsetsize"}],
		"rt_sigprocmask":       [{ptype: "int", pname: "how"}, {ptype: "sigset_t*", pname: "set"}, {ptype: "sigset_t*", pname: "oldset"}, {ptype: "size_t", pname: "sigsetsize"}],
		"rt_sigreturn":         [],
		"ioctl":               [{ptype: "int", pname: "fd"}, {ptype: "unsigned long", pname: "request"}, {ptype: "unsigned long", pname: "arg"}, {ptype: "const char*", pname: "pathname"}],
		"pread64":             [{ptype: "int", pname: "fd"}, {ptype: "void*", pname: "buf"}, {ptype: "size_t", pname: "count"}, {ptype: "off_t", pname: "offset"}, {ptype: "const char*", pname: "pathname"}],
		"pwrite64":            [{ptype: "int", pname: "fd"}, {ptype: "const void*", pname: "buf"}, {ptype: "size_t", pname: "count"}, {ptype: "off_t", pname: "offset"}, {ptype: "const char*", pname: "pathname"}],
		"readv":               [{ptype: "int", pname: "fd"}, {ptype: "const struct iovec*", pname: "iov"}, {ptype: "int", pname: "iovcnt"}, {ptype: "const char*", pname: "pathname"}],
		"writev":              [{ptype: "int", pname: "fd"}, {ptype: "const struct iovec*", pname: "iov"}, {ptype: "int", pname: "iovcnt"}, {ptype: "const char*", pname: "pathname"}],
		"access":              [{ptype: "const char*", pname: "pathname"}, {ptype: "int", pname: "mode"}],
		"pipe":                [{ptype: "int[2]", pname: "pipefd"}],
		"select":              [{ptype: "int", pname: "nfds"}, {ptype: "fd_set*", pname: "readfds"}, {ptype: "fd_set*", pname: "writefds"}, {ptype: "fd_set*", pname: "exceptfds"}, {ptype: "struct timeval*", pname: "timeout"}],
		"sched_yield":          [],
		"mremap":              [{ptype: "void*", pname: "old_address"}, {ptype: "size_t", pname: "old_size"}, {ptype: "size_t", pname: "new_size"}, {ptype: "int", pname: "flags"}, {ptype: "void*", pname: "new_address"}],
		"msync":               [{ptype: "void*", pname: "addr"}, {ptype: "size_t", pname: "length"}, {ptype: "int", pname: "flags"}],
		"mincore":             [{ptype: "void*", pname: "addr"}, {ptype: "size_t", pname: "length"}, {ptype: "unsigned char*", pname: "vec"}],
		"madvise":             [{ptype: "void*", pname: "addr"}, {ptype: "size_t", pname: "length"}, {ptype: "int", pname: "advice"}],
		"shmget":              [{ptype: "key_t", pname: "key"}, {ptype: "size_t", pname: "size"}, {ptype: "int", pname: "shmflg"}],
		"shmat":               [{ptype: "int", pname: "shmid"}, {ptype: "const void*", pname: "shmaddr"}, {ptype: "int", pname: "shmflg"}],
		"shmctl":              [{ptype: "int", pname: "shmid"}, {ptype: "int", pname: "cmd"}, {ptype: "struct shmid_ds*", pname: "buf"}],
		"dup":                 [{ptype: "int", pname: "oldfd"}],
		"dup2":                [{ptype: "int", pname: "oldfd"}, {ptype: "int", pname: "newfd"}],
		"pause":               [],
		"nanosleep":           [{ptype: "const struct timespec*", pname: "req"}, {ptype: "struct timespec*", pname: "rem"}],
		"getitimer":           [{ptype: "int", pname: "which"}, {ptype: "struct itimerval*", pname: "curr_value"}],
		"alarm":               [{ptype: "unsigned int", pname: "seconds"}],
		"setitimer":           [{ptype: "int", pname: "which"}, {ptype: "struct itimerval*", pname: "new_value"}, {ptype: "struct itimerval*", pname: "old_value"}],
		"getpid":              [],
		"sendfile":            [{ptype: "int", pname: "out_fd"}, {ptype: "int", pname: "in_fd"}, {ptype: "off_t*", pname: "offset"}, {ptype: "size_t", pname: "count"}],
		"socket":              [{ptype: "int", pname: "domain"}, {ptype: "int", pname: "type"}, {ptype: "int", pname: "protocol"}],
		"connect":             [{ptype: "int", pname: "sockfd"}, {ptype: "struct sockaddr*", pname: "addr"}, {ptype: "int", pname: "addrlen"}],
		"accept":              [{ptype: "int", pname: "sockfd"}, {ptype: "struct sockaddr*", pname: "addr"}, {ptype: "int*", pname: "addrlen"}],
		"sendto":              [{ptype: "int", pname: "sockfd"}, {ptype: "void*", pname: "buf"}, {ptype: "size_t", pname: "len"}, {ptype: "int", pname: "flags"}, {ptype: "struct sockaddr*", pname: "dest_addr"}, {ptype: "int", pname: "addrlen"}],
		"recvfrom":            [{ptype: "int", pname: "sockfd"}, {ptype: "void*", pname: "buf"}, {ptype: "size_t", pname: "len"}, {ptype: "int", pname: "flags"}, {ptype: "struct sockaddr*", pname: "src_addr"}, {ptype: "int*", pname: "addrlen"}],
		"sendmsg":             [{ptype: "int", pname: "sockfd"}, {ptype: "struct msghdr*", pname: "msg"}, {ptype: "int", pname: "flags"}],
		"recvmsg":             [{ptype: "int", pname: "sockfd"}, {ptype: "struct msghdr*", pname: "msg"}, {ptype: "int", pname: "flags"}],
		"shutdown":            [{ptype: "int", pname: "sockfd"}, {ptype: "int", pname: "how"}],
		"bind":                [{ptype: "int", pname: "sockfd"}, {ptype: "struct sockaddr*", pname: "addr"}, {ptype: "int", pname: "addrlen"}],
		"listen":              [{ptype: "int", pname: "sockfd"}, {ptype: "int", pname: "backlog"}],
		"getsockname":         [{ptype: "int", pname: "sockfd"}, {ptype: "struct sockaddr*", pname: "addr"}, {ptype: "int*", pname: "addrlen"}],
		"getpeername":         [{ptype: "int", pname: "sockfd"}, {ptype: "struct sockaddr*", pname: "addr"}, {ptype: "int*", pname: "addrlen"}],
		"socketpair":          [{ptype: "int", pname: "domain"}, {ptype: "int", pname: "type"}, {ptype: "int", pname: "protocol"}, {ptype: "int[2]", pname: "sv"}],
		"setsockopt":          [{ptype: "int", pname: "sockfd"}, {ptype: "int", pname: "level"}, {ptype: "int", pname: "optname"}, {ptype: "const void*", pname: "optval"}, {ptype: "int", pname: "optlen"}],
		"getsockopt":          [{ptype: "int", pname: "sockfd"}, {ptype: "int", pname: "level"}, {ptype: "int", pname: "optname"}, {ptype: "char*", pname: "optval"}, {ptype: "int*", pname: "optlen"}],
		"clone":               [{ptype: "unsigned long", pname: "flags"}, {ptype: "void*", pname: "stack"}, {ptype: "int*", pname: "parent_tid"}, {ptype: "int*", pname: "child_tid"}, {ptype: "unsigned long", pname: "tls"}],
		"fork":                [],
		"vfork":               [],
		"execve":              [{ptype: "const char*", pname: "pathname"}, {ptype: "const char*const*", pname: "argv"}, {ptype: "const char*const*", pname: "envp"}],
		"exit":                [{ptype: "int", pname: "status"}],
		"wait4":               [{ptype: "pid_t", pname: "pid"}, {ptype: "int*", pname: "wstatus"}, {ptype: "int", pname: "options"}, {ptype: "struct rusage*", pname: "rusage"}],
		"kill":                [{ptype: "pid_t", pname: "pid"}, {ptype: "int", pname: "sig"}],
		"uname":               [{ptype: "struct utsname*", pname: "buf"}],
		"semget":              [{ptype: "key_t", pname: "key"}, {ptype: "int", pname: "nsems"}, {ptype: "int", pname: "semflg"}],
		"semop":               [{ptype: "int", pname: "semid"}, {ptype: "struct sembuf*", pname: "sops"}, {ptype: "size_t", pname: "nsops"}],
		"semctl":              [{ptype: "int", pname: "semid"}, {ptype: "int", pname: "semnum"}, {ptype: "int", pname: "cmd"}, {ptype: "unsigned long", pname: "arg"}],
		"shmdt":               [{ptype: "const void*", pname: "shmaddr"}],
		"msgget":              [{ptype: "key_t", pname: "key"}, {ptype: "int", pname: "msgflg"}],
		"msgsnd":              [{ptype: "int", pname: "msqid"}, {ptype: "struct msgbuf*", pname: "msgp"}, {ptype: "size_t", pname: "msgsz"}, {ptype: "int", pname: "msgflg"}],
		"msgrcv":              [{ptype: "int", pname: "msqid"}, {ptype: "struct msgbuf*", pname: "msgp"}, {ptype: "size_t", pname: "msgsz"}, {ptype: "long", pname: "msgtyp"}, {ptype: "int", pname: "msgflg"}],
		"msgctl":              [{ptype: "int", pname: "msqid"}, {ptype: "int", pname: "cmd"}, {ptype: "struct msqid_ds*", pname: "buf"}],
		"fcntl":               [{ptype: "int", pname: "fd"}, {ptype: "int", pname: "cmd"}, {ptype: "unsigned long", pname: "arg"}, {ptype: "const char*", pname: "pathname"}],
		"flock":               [{ptype: "int", pname: "fd"}, {ptype: "int", pname: "operation"}, {ptype: "const char*", pname: "pathname"}],
		"fsync":               [{ptype: "int", pname: "fd"}, {ptype: "const char*", pname: "pathname"}],
		"fdatasync":           [{ptype: "int", pname: "fd"}, {ptype: "const char*", pname: "pathname"}],
		"truncate":            [{ptype: "const char*", pname: "path"}, {ptype: "off_t", pname: "length"}],
		"ftruncate":           [{ptype: "int", pname: "fd"}, {ptype: "off_t", pname: "length"}],
		"getdents":            [{ptype: "int", pname: "fd"}, {ptype: "struct linux_dirent*", pname: "dirp"}, {ptype: "unsigned int", pname: "count"}],
		"getcwd":              [{ptype: "char*", pname: "buf"}, {ptype: "size_t", pname: "size"}],
		"chdir":               [{ptype: "const char*", pname: "path"}],
		"fchdir":              [{ptype: "int", pname: "fd"}, {ptype: "const char*", pname: "pathname"}],
		"rename":              [{ptype: "const char*", pname: "oldpath"}, {ptype: "const char*", pname: "newpath"}],
		"mkdir":               [{ptype: "const char*", pname: "pathname"}, {ptype: "mode_t", pname: "mode"}],
		"rmdir":               [{ptype: "const char*", pname: "pathname"}],
		"creat":               [{ptype: "const char*", pname: "pathname"}, {ptype: "mode_t", pname: "mode"}],
		"link":                [{ptype: "const char*", pname: "oldpath"}, {ptype: "const char*", pname: "newpath"}],
		"unlink":              [{ptype: "const char*", pname: "pathname"}],
		"symlink":             [{ptype: "const char*", pname: "target"}, {ptype: "const char*", pname: "linkpath"}],
		"readlink":            [{ptype: "const char*", pname: "pathname"}, {ptype: "char*", pname: "buf"}, {ptype: "size_t", pname: "bufsiz"}],
		"chmod":               [{ptype: "const char*", pname: "pathname"}, {ptype: "mode_t", pname: "mode"}],
		"fchmod":              [{ptype: "int", pname: "fd"}, {ptype: "mode_t", pname: "mode"}, {ptype: "const char*", pname: "pathname"}],
		"chown":               [{ptype: "const char*", pname: "pathname"}, {ptype: "uid_t", pname: "owner"}, {ptype: "gid_t", pname: "group"}],
		"fchown":              [{ptype: "int", pname: "fd"}, {ptype: "uid_t", pname: "owner"}, {ptype: "gid_t", pname: "group"}, {ptype: "const char*", pname: "pathname"}],
		"lchown":              [{ptype: "const char*", pname: "pathname"}, {ptype: "uid_t", pname: "owner"}, {ptype: "gid_t", pname: "group"}],
		"umask":               [{ptype: "mode_t", pname: "mask"}],
		"gettimeofday":        [{ptype: "struct timeval*", pname: "tv"}, {ptype: "struct timezone*", pname: "tz"}],
		"getrlimit":           [{ptype: "int", pname: "resource"}, {ptype: "struct rlimit*", pname: "rlim"}],
		"getrusage":           [{ptype: "int", pname: "who"}, {ptype: "struct rusage*", pname: "usage"}],
		"sysinfo":             [{ptype: "struct sysinfo*", pname: "info"}],
		"times":               [{ptype: "struct tms*", pname: "buf"}],
		"ptrace":              [{ptype: "long", pname: "request"}, {ptype: "pid_t", pname: "pid"}, {ptype: "void*", pname: "addr"}, {ptype: "void*", pname: "data"}],
		"getuid":              [],
		"syslog":              [{ptype: "int", pname: "type"}, {ptype: "char*", pname: "bufp"}, {ptype: "int", pname: "len"}],
		"getgid":              [],
		"setuid":              [{ptype: "uid_t", pname: "uid"}],
		"setgid":              [{ptype: "gid_t", pname: "gid"}],
		"geteuid":             [],
		"getegid":             [],
		"setpgid":             [{ptype: "pid_t", pname: "pid"}, {ptype: "pid_t", pname: "pgid"}],
		"getppid":             [],
		"getpgrp":             [],
		"setsid":              [],
		"setreuid":            [{ptype: "uid_t", pname: "ruid"}, {ptype: "uid_t", pname: "euid"}],
		"setregid":            [{ptype: "gid_t", pname: "rgid"}, {ptype: "gid_t", pname: "egid"}],
		"getgroups":           [{ptype: "int", pname: "size"}, {ptype: "gid_t*", pname: "list"}],
		"setgroups":           [{ptype: "int", pname: "size"}, {ptype: "gid_t*", pname: "list"}],
		"setresuid":           [{ptype: "uid_t", pname: "ruid"}, {ptype: "uid_t", pname: "euid"}, {ptype: "uid_t", pname: "suid"}],
		"getresuid":           [{ptype: "uid_t*", pname: "ruid"}, {ptype: "uid_t*", pname: "euid"}, {ptype: "uid_t*", pname: "suid"}],
		"setresgid":           [{ptype: "gid_t", pname: "rgid"}, {ptype: "gid_t", pname: "egid"}, {ptype: "gid_t", pname: "sgid"}],
		"getresgid":           [{ptype: "gid_t*", pname: "rgid"}, {ptype: "gid_t*", pname: "egid"}, {ptype: "gid_t*", pname: "sgid"}],
		"getpgid":             [{ptype: "pid_t", pname: "pid"}],
		"setfsuid":            [{ptype: "uid_t", pname: "fsuid"}],
		"setfsgid":            [{ptype: "gid_t", pname: "fsgid"}],
		"getsid":              [{ptype: "pid_t", pname: "pid"}],
		"capget":              [{ptype: "cap_user_header_t", pname: "hdrp"}, {ptype: "cap_user_data_t", pname: "datap"}],
		"capset":              [{ptype: "cap_user_header_t", pname: "hdrp"}, {ptype: "const cap_user_data_t", pname: "datap"}],
		"rtsigpending":        [{ptype: "sigset_t*", pname: "set"}, {ptype: "size_t", pname: "sigsetsize"}],
		"rtsigtimedwait":      [{ptype: "const sigset_t*", pname: "set"}, {ptype: "siginfo_t*", pname: "info"}, {ptype: "const struct timespec*", pname: "timeout"}, {ptype: "size_t", pname: "sigsetsize"}],
		"rtsigqueueinfo":      [{ptype: "pid_t", pname: "tgid"}, {ptype: "int", pname: "sig"}, {ptype: "siginfo_t*", pname: "info"}],
		"rtsigsuspend":        [{ptype: "sigset_t*", pname: "mask"}, {ptype: "size_t", pname: "sigsetsize"}],
		"sigaltstack":         [{ptype: "const stack_t*", pname: "ss"}, {ptype: "stack_t*", pname: "old_ss"}],
		"utime":               [{ptype: "const char*", pname: "filename"}, {ptype: "const struct utimbuf*", pname: "times"}],
		"mknod":               [{ptype: "const char*", pname: "pathname"}, {ptype: "mode_t", pname: "mode"}, {ptype: "dev_t", pname: "dev"}],
		"uselib":              [{ptype: "const char*", pname: "library"}],
		"personality":         [{ptype: "unsigned long", pname: "persona"}],
		"ustat":               [{ptype: "dev_t", pname: "dev"}, {ptype: "struct ustat*", pname: "ubuf"}],
		"statfs":              [{ptype: "const char*", pname: "path"}, {ptype: "struct statfs*", pname: "buf"}],
		"fstatfs":             [{ptype: "int", pname: "fd"}, {ptype: "struct statfs*", pname: "buf"}, {ptype: "const char*", pname: "pathname"}],
		"sysfs":               [{ptype: "int", pname: "option"}],
		"getpriority":         [{ptype: "int", pname: "which"}, {ptype: "int", pname: "who"}],
		"setpriority":         [{ptype: "int", pname: "which"}, {ptype: "int", pname: "who"}, {ptype: "int", pname: "prio"}],
		"schedsetparam":       [{ptype: "pid_t", pname: "pid"}, {ptype: "struct sched_param*", pname: "param"}],
		"schedgetparam":       [{ptype: "pid_t", pname: "pid"}, {ptype: "struct sched_param*", pname: "param"}],
		"schedsetscheduler":   [{ptype: "pid_t", pname: "pid"}, {ptype: "int", pname: "policy"}, {ptype: "struct sched_param*", pname: "param"}],
		"schedgetscheduler":   [{ptype: "pid_t", pname: "pid"}],
		"schedgetprioritymax": [{ptype: "int", pname: "policy"}],
		"schedgetprioritymin": [{ptype: "int", pname: "policy"}],
		"schedrrgetinterval":  [{ptype: "pid_t", pname: "pid"}, {ptype: "struct timespec*", pname: "tp"}],
		"mlock":               [{ptype: "const void*", pname: "addr"}, {ptype: "size_t", pname: "len"}],
		"munlock":             [{ptype: "const void*", pname: "addr"}, {ptype: "size_t", pname: "len"}],
		"mlockall":            [{ptype: "int", pname: "flags"}],
		"munlockall":          [],
		"vhangup":             [],
		"modifyldt":           [{ptype: "int", pname: "func"}, {ptype: "void*", pname: "ptr"}, {ptype: "unsigned long", pname: "bytecount"}],
		"pivotroot":           [{ptype: "const char*", pname: "new_root"}, {ptype: "const char*", pname: "put_old"}],
		"sysctl":              [{ptype: "struct __sysctl_args*", pname: "args"}],
		"prctl":               [{ptype: "int", pname: "option"}, {ptype: "unsigned long", pname: "arg2"}, {ptype: "unsigned long", pname: "arg3"}, {ptype: "unsigned long", pname: "arg4"}, {ptype: "unsigned long", pname: "arg5"}],
		"arch_prctl":           [{ptype: "int", pname: "option"}, {ptype: "unsigned long", pname: "addr"}],
		"adjtimex":            [{ptype: "struct timex*", pname: "buf"}],
		"setrlimit":           [{ptype: "int", pname: "resource"}, {ptype: "const struct rlimit*", pname: "rlim"}],
		"chroot":              [{ptype: "const char*", pname: "path"}],
		"sync":                [],
		"acct":                [{ptype: "const char*", pname: "filename"}],
		"settimeofday":        [{ptype: "const struct timeval*", pname: "tv"}, {ptype: "const struct timezone*", pname: "tz"}],
		"mount":               [{ptype: "const char*", pname: "source"}, {ptype: "const char*", pname: "target"}, {ptype: "const char*", pname: "filesystemtype"}, {ptype: "unsigned long", pname: "mountflags"}, {ptype: "const void*", pname: "data"}],
		"umount":              [{ptype: "const char*", pname: "target"}, {ptype: "int", pname: "flags"}],
		"swapon":              [{ptype: "const char*", pname: "path"}, {ptype: "int", pname: "swapflags"}],
		"swapoff":             [{ptype: "const char*", pname: "path"}],
		"reboot":              [{ptype: "int", pname: "magic"}, {ptype: "int", pname: "magic2"}, {ptype: "int", pname: "cmd"}, {ptype: "void*", pname: "arg"}],
		"sethostname":         [{ptype: "const char*", pname: "name"}, {ptype: "size_t", pname: "len"}],
		"setdomainname":       [{ptype: "const char*", pname: "name"}, {ptype: "size_t", pname: "len"}],
		"iopl":                [{ptype: "int", pname: "level"}],
		"ioperm":              [{ptype: "unsigned long", pname: "from"}, {ptype: "unsigned long", pname: "num"}, {ptype: "int", pname: "turn_on"}],
		"create_module":		[],
		"init_module":          [{ptype: "void*", pname: "module_image"}, {ptype: "unsigned long", pname: "len"}, {ptype: "const char*", pname: "param_values"}],
		"delete_module":        [{ptype: "const char*", pname: "name"}, {ptype: "int", pname: "flags"}],
		"get_kernel_syms":		[],
		"query_module":			[],
		"quotactl":            [{ptype: "int", pname: "cmd"}, {ptype: "const char*", pname: "special"}, {ptype: "int", pname: "id"}, {ptype: "void*", pname: "addr"}],
		"nfsservctl":			[],
		"getpmsg":				[],
		"putpmsg":				[],
		"afs_syscall":			[],
		"tuxcall":				[],
		"security":				[],
		"gettid":              [],
		"readahead":           [{ptype: "int", pname: "fd"}, {ptype: "off_t", pname: "offset"}, {ptype: "size_t", pname: "count"}, {ptype: "const char*", pname: "pathname"}],
		"setxattr":            [{ptype: "const char*", pname: "path"}, {ptype: "const char*", pname: "name"}, {ptype: "const void*", pname: "value"}, {ptype: "size_t", pname: "size"}, {ptype: "int", pname: "flags"}],
		"lsetxattr":           [{ptype: "const char*", pname: "path"}, {ptype: "const char*", pname: "name"}, {ptype: "const void*", pname: "value"}, {ptype: "size_t", pname: "size"}, {ptype: "int", pname: "flags"}],
		"fsetxattr":           [{ptype: "int", pname: "fd"}, {ptype: "const char*", pname: "name"}, {ptype: "const void*", pname: "value"}, {ptype: "size_t", pname: "size"}, {ptype: "int", pname: "flags"}],
		"getxattr":            [{ptype: "const char*", pname: "path"}, {ptype: "const char*", pname: "name"}, {ptype: "void*", pname: "value"}, {ptype: "size_t", pname: "size"}],
		"lgetxattr":           [{ptype: "const char*", pname: "path"}, {ptype: "const char*", pname: "name"}, {ptype: "void*", pname: "value"}, {ptype: "size_t", pname: "size"}],
		"fgetxattr":           [{ptype: "int", pname: "fd"}, {ptype: "const char*", pname: "name"}, {ptype: "void*", pname: "value"}, {ptype: "size_t", pname: "size"}],
		"listxattr":           [{ptype: "const char*", pname: "path"}, {ptype: "char*", pname: "list"}, {ptype: "size_t", pname: "size"}],
		"llistxattr":          [{ptype: "const char*", pname: "path"}, {ptype: "char*", pname: "list"}, {ptype: "size_t", pname: "size"}],
		"flistxattr":          [{ptype: "int", pname: "fd"}, {ptype: "char*", pname: "list"}, {ptype: "size_t", pname: "size"}],
		"removexattr":         [{ptype: "const char*", pname: "path"}, {ptype: "const char*", pname: "name"}],
		"lremovexattr":        [{ptype: "const char*", pname: "path"}, {ptype: "const char*", pname: "name"}],
		"fremovexattr":        [{ptype: "int", pname: "fd"}, {ptype: "const char*", pname: "name"}],
		"tkill":               [{ptype: "int", pname: "tid"}, {ptype: "int", pname: "sig"}],
		"time":                [{ptype: "time_t*", pname: "tloc"}],
		"futex":               [{ptype: "int*", pname: "uaddr"}, {ptype: "int", pname: "futex_op"}, {ptype: "int", pname: "val"}, {ptype: "const struct timespec*", pname: "timeout"}, {ptype: "int*", pname: "uaddr2"}, {ptype: "int", pname: "val3"}],
		"sched_setaffinity":    [{ptype: "pid_t", pname: "pid"}, {ptype: "size_t", pname: "cpusetsize"}, {ptype: "unsigned long*", pname: "mask"}],
		"sched_getaffinity":    [{ptype: "pid_t", pname: "pid"}, {ptype: "size_t", pname: "cpusetsize"}, {ptype: "unsigned long*", pname: "mask"}],
		"setthreadarea":       [{ptype: "struct user_desc*", pname: "u_info"}],
		"io_setup":             [{ptype: "unsigned int", pname: "nr_events"}, {ptype: "io_context_t*", pname: "ctx_idp"}],
		"io_destroy":           [{ptype: "io_context_t", pname: "ctx_id"}],
		"io_getevents":         [{ptype: "io_context_t", pname: "ctx_id"}, {ptype: "long", pname: "min_nr"}, {ptype: "long", pname: "nr"}, {ptype: "struct io_event*", pname: "events"}, {ptype: "struct timespec*", pname: "timeout"}],
		"io_submit":            [{ptype: "io_context_t", pname: "ctx_id"}, {ptype: "long", pname: "nr"}, {ptype: "struct iocb**", pname: "iocbpp"}],
		"io_cancel":            [{ptype: "io_context_t", pname: "ctx_id"}, {ptype: "struct iocb*", pname: "iocb"}, {ptype: "struct io_event*", pname: "result"}],
		"getthreadarea":       [{ptype: "struct user_desc*", pname: "u_info"}],
		"lookupdcookie":       [{ptype: "u64", pname: "cookie"}, {ptype: "char*", pname: "buffer"}, {ptype: "size_t", pname: "len"}],
		"epoll_create":         [{ptype: "int", pname: "size"}],
		"epoll_ctl_old":		[],
		"epoll_wait_old":		[],
		"remapfilepages":      [{ptype: "void*", pname: "addr"}, {ptype: "size_t", pname: "size"}, {ptype: "int", pname: "prot"}, {ptype: "size_t", pname: "pgoff"}, {ptype: "int", pname: "flags"}],
		"getdents64":          [{ptype: "unsigned int", pname: "fd"}, {ptype: "struct linux_dirent64*", pname: "dirp"}, {ptype: "unsigned int", pname: "count"}],
		"set_tid_address":       [{ptype: "int*", pname: "tidptr"}],
		"restartsyscall":      [],
		"semtimedop":          [{ptype: "int", pname: "semid"}, {ptype: "struct sembuf*", pname: "sops"}, {ptype: "size_t", pname: "nsops"}, {ptype: "const struct timespec*", pname: "timeout"}],
		"fadvise64":           [{ptype: "int", pname: "fd"}, {ptype: "off_t", pname: "offset"}, {ptype: "size_t", pname: "len"}, {ptype: "int", pname: "advice"}, {ptype: "const char*", pname: "pathname"}],
		"timercreate":         [{ptype: "const clockid_t", pname: "clockid"}, {ptype: "struct sigevent*", pname: "sevp"}, {ptype: "timer_t*", pname: "timer_id"}],
		"timersettime":        [{ptype: "timer_t", pname: "timer_id"}, {ptype: "int", pname: "flags"}, {ptype: "const struct itimerspec*", pname: "new_value"}, {ptype: "struct itimerspec*", pname: "old_value"}],
		"timergettime":        [{ptype: "timer_t", pname: "timer_id"}, {ptype: "struct itimerspec*", pname: "curr_value"}],
		"timergetoverrun":     [{ptype: "timer_t", pname: "timer_id"}],
		"timerdelete":         [{ptype: "timer_t", pname: "timer_id"}],
		"clock_settime":        [{ptype: "const clockid_t", pname: "clockid"}, {ptype: "const struct timespec*", pname: "tp"}],
		"clock_gettime":        [{ptype: "const clockid_t", pname: "clockid"}, {ptype: "struct timespec*", pname: "tp"}],
		"clock_getres":         [{ptype: "const clockid_t", pname: "clockid"}, {ptype: "struct timespec*", pname: "res"}],
		"clock_nanosleep":      [{ptype: "const clockid_t", pname: "clockid"}, {ptype: "int", pname: "flags"}, {ptype: "const struct timespec*", pname: "request"}, {ptype: "struct timespec*", pname: "remain"}],
		"exitgroup":           [{ptype: "int", pname: "status"}],
		"epoll_wait":           [{ptype: "int", pname: "epfd"}, {ptype: "struct epoll_event*", pname: "events"}, {ptype: "int", pname: "maxevents"}, {ptype: "int", pname: "timeout"}],
		"epoll_ctl":            [{ptype: "int", pname: "epfd"}, {ptype: "int", pname: "op"}, {ptype: "int", pname: "fd"}, {ptype: "struct epoll_event*", pname: "event"}, {ptype: "const char*", pname: "pathname"}],
		"tgkill":              [{ptype: "int", pname: "tgid"}, {ptype: "int", pname: "tid"}, {ptype: "int", pname: "sig"}],
		"utimes":              [{ptype: "char*", pname: "filename"}, {ptype: "struct timeval*", pname: "times"}],
		"vserver":				[],
		"mbind":               [{ptype: "void*", pname: "addr"}, {ptype: "unsigned long", pname: "len"}, {ptype: "int", pname: "mode"}, {ptype: "const unsigned long*", pname: "nodemask"}, {ptype: "unsigned long", pname: "maxnode"}, {ptype: "unsigned int", pname: "flags"}],
		"setmempolicy":        [{ptype: "int", pname: "mode"}, {ptype: "const unsigned long*", pname: "nodemask"}, {ptype: "unsigned long", pname: "maxnode"}],
		"getmempolicy":        [{ptype: "int*", pname: "mode"}, {ptype: "unsigned long*", pname: "nodemask"}, {ptype: "unsigned long", pname: "maxnode"}, {ptype: "void*", pname: "addr"}, {ptype: "unsigned long", pname: "flags"}],
		"mqopen":              [{ptype: "const char*", pname: "name"}, {ptype: "int", pname: "oflag"}, {ptype: "mode_t", pname: "mode"}, {ptype: "struct mq_attr*", pname: "attr"}],
		"mqunlink":            [{ptype: "const char*", pname: "name"}],
		"mqtimedsend":         [{ptype: "mqd_t", pname: "mqdes"}, {ptype: "const char*", pname: "msg_ptr"}, {ptype: "size_t", pname: "msg_len"}, {ptype: "unsigned int", pname: "msg_prio"}, {ptype: "const struct timespec*", pname: "abs_timeout"}],
		"mqtimedreceive":      [{ptype: "mqd_t", pname: "mqdes"}, {ptype: "char*", pname: "msg_ptr"}, {ptype: "size_t", pname: "msg_len"}, {ptype: "unsigned int*", pname: "msg_prio"}, {ptype: "const struct timespec*", pname: "abs_timeout"}],
		"mqnotify":            [{ptype: "mqd_t", pname: "mqdes"}, {ptype: "const struct sigevent*", pname: "sevp"}],
		"mqgetsetattr":        [{ptype: "mqd_t", pname: "mqdes"}, {ptype: "const struct mq_attr*", pname: "newattr"}, {ptype: "struct mq_attr*", pname: "oldattr"}],
		"kexecload":           [{ptype: "unsigned long", pname: "entry"}, {ptype: "unsigned long", pname: "nr_segments"}, {ptype: "struct kexec_segment*", pname: "segments"}, {ptype: "unsigned long", pname: "flags"}],
		"waitid":              [{ptype: "int", pname: "idtype"}, {ptype: "pid_t", pname: "id"}, {ptype: "struct siginfo*", pname: "infop"}, {ptype: "int", pname: "options"}, {ptype: "struct rusage*", pname: "rusage"}],
		"addkey":              [{ptype: "const char*", pname: "type"}, {ptype: "const char*", pname: "description"}, {ptype: "const void*", pname: "payload"}, {ptype: "size_t", pname: "plen"}, {ptype: "key_serial_t", pname: "keyring"}],
		"requestkey":          [{ptype: "const char*", pname: "type"}, {ptype: "const char*", pname: "description"}, {ptype: "const char*", pname: "callout_info"}, {ptype: "key_serial_t", pname: "dest_keyring"}],
		"keyctl":              [{ptype: "int", pname: "operation"}, {ptype: "unsigned long", pname: "arg2"}, {ptype: "unsigned long", pname: "arg3"}, {ptype: "unsigned long", pname: "arg4"}, {ptype: "unsigned long", pname: "arg5"}],
		"ioprioset":           [{ptype: "int", pname: "which"}, {ptype: "int", pname: "who"}, {ptype: "int", pname: "ioprio"}],
		"ioprioget":           [{ptype: "int", pname: "which"}, {ptype: "int", pname: "who"}],
		"inotify_init":         [],
		"inotify_add_watch":     [{ptype: "int", pname: "fd"}, {ptype: "const char*", pname: "pathname"}, {ptype: "u32", pname: "mask"}],
		"inotify_rm_watch":      [{ptype: "int", pname: "fd"}, {ptype: "int", pname: "wd"}],
		"migratepages":        [{ptype: "int", pname: "pid"}, {ptype: "unsigned long", pname: "maxnode"}, {ptype: "const unsigned long*", pname: "old_nodes"}, {ptype: "const unsigned long*", pname: "new_nodes"}],
		"openat":              [{ptype: "int", pname: "dirfd"}, {ptype: "const char*", pname: "pathname"}, {ptype: "int", pname: "flags"}, {ptype: "mode_t", pname: "mode"}],
		"mkdirat":             [{ptype: "int", pname: "dirfd"}, {ptype: "const char*", pname: "pathname"}, {ptype: "mode_t", pname: "mode"}],
		"mknodat":             [{ptype: "int", pname: "dirfd"}, {ptype: "const char*", pname: "pathname"}, {ptype: "mode_t", pname: "mode"}, {ptype: "dev_t", pname: "dev"}],
		"fchownat":            [{ptype: "int", pname: "dirfd"}, {ptype: "const char*", pname: "pathname"}, {ptype: "uid_t", pname: "owner"}, {ptype: "gid_t", pname: "group"}, {ptype: "int", pname: "flags"}],
		"futimesat":           [{ptype: "int", pname: "dirfd"}, {ptype: "const char*", pname: "pathname"}, {ptype: "struct timeval*", pname: "times"}],
		"newfstatat":          [{ptype: "int", pname: "dirfd"}, {ptype: "const char*", pname: "pathname"}, {ptype: "struct stat*", pname: "statbuf"}, {ptype: "int", pname: "flags"}],
		"unlinkat":            [{ptype: "int", pname: "dirfd"}, {ptype: "const char*", pname: "pathname"}, {ptype: "int", pname: "flags"}],
		"renameat":            [{ptype: "int", pname: "olddirfd"}, {ptype: "const char*", pname: "oldpath"}, {ptype: "int", pname: "newdirfd"}, {ptype: "const char*", pname: "newpath"}],
		"linkat":              [{ptype: "int", pname: "olddirfd"}, {ptype: "const char*", pname: "oldpath"}, {ptype: "int", pname: "newdirfd"}, {ptype: "const char*", pname: "newpath"}, {ptype: "unsigned int", pname: "flags"}],
		"symlinkat":           [{ptype: "const char*", pname: "target"}, {ptype: "int", pname: "newdirfd"}, {ptype: "const char*", pname: "linkpath"}],
		"readlinkat":          [{ptype: "int", pname: "dirfd"}, {ptype: "const char*", pname: "pathname"}, {ptype: "char*", pname: "buf"}, {ptype: "int", pname: "bufsiz"}],
		"fchmodat":            [{ptype: "int", pname: "dirfd"}, {ptype: "const char*", pname: "pathname"}, {ptype: "mode_t", pname: "mode"}, {ptype: "int", pname: "flags"}],
		"faccessat":           [{ptype: "int", pname: "dirfd"}, {ptype: "const char*", pname: "pathname"}, {ptype: "int", pname: "mode"}, {ptype: "int", pname: "flags"}],
		"pselect6":            [{ptype: "int", pname: "nfds"}, {ptype: "fd_set*", pname: "readfds"}, {ptype: "fd_set*", pname: "writefds"}, {ptype: "fd_set*", pname: "exceptfds"}, {ptype: "struct timespec*", pname: "timeout"}, {ptype: "void*", pname: "sigmask"}],
		"ppoll":               [{ptype: "struct pollfd*", pname: "fds"}, {ptype: "unsigned int", pname: "nfds"}, {ptype: "struct timespec*", pname: "tmo_p"}, {ptype: "const sigset_t*", pname: "sigmask"}, {ptype: "size_t", pname: "sigsetsize"}],
		"unshare":             [{ptype: "int", pname: "flags"}],
		"set_robust_list":       [{ptype: "struct robust_list_head*", pname: "head"}, {ptype: "size_t", pname: "len"}],
		"get_robust_list":       [{ptype: "int", pname: "pid"}, {ptype: "struct robust_list_head**", pname: "head_ptr"}, {ptype: "size_t*", pname: "len_ptr"}],
		"splice":              [{ptype: "int", pname: "fd_in"}, {ptype: "off_t*", pname: "off_in"}, {ptype: "int", pname: "fd_out"}, {ptype: "off_t*", pname: "off_out"}, {ptype: "size_t", pname: "len"}, {ptype: "unsigned int", pname: "flags"}],
		"tee":                 [{ptype: "int", pname: "fd_in"}, {ptype: "int", pname: "fd_out"}, {ptype: "size_t", pname: "len"}, {ptype: "unsigned int", pname: "flags"}],
		"syncfilerange":       [{ptype: "int", pname: "fd"}, {ptype: "off_t", pname: "offset"}, {ptype: "off_t", pname: "nbytes"}, {ptype: "unsigned int", pname: "flags"}],
		"vmsplice":            [{ptype: "int", pname: "fd"}, {ptype: "const struct iovec*", pname: "iov"}, {ptype: "unsigned long", pname: "nr_segs"}, {ptype: "unsigned int", pname: "flags"}],
		"movepages":           [{ptype: "int", pname: "pid"}, {ptype: "unsigned long", pname: "count"}, {ptype: "const void**", pname: "pages"}, {ptype: "const int*", pname: "nodes"}, {ptype: "int*", pname: "status"}, {ptype: "int", pname: "flags"}],
		"utimensat":           [{ptype: "int", pname: "dirfd"}, {ptype: "const char*", pname: "pathname"}, {ptype: "struct timespec*", pname: "times"}, {ptype: "int", pname: "flags"}],
		"epoll_pwait":          [{ptype: "int", pname: "epfd"}, {ptype: "struct epoll_event*", pname: "events"}, {ptype: "int", pname: "maxevents"}, {ptype: "int", pname: "timeout"}, {ptype: "const sigset_t*", pname: "sigmask"}, {ptype: "size_t", pname: "sigsetsize"}],
		"signalfd":            [{ptype: "int", pname: "fd"}, {ptype: "sigset_t*", pname: "mask"}, {ptype: "int", pname: "flags"}],
		"timerfd_create":       [{ptype: "int", pname: "clockid"}, {ptype: "int", pname: "flags"}],
		"eventfd":             [{ptype: "unsigned int", pname: "initval"}, {ptype: "int", pname: "flags"}],
		"fallocate":           [{ptype: "int", pname: "fd"}, {ptype: "int", pname: "mode"}, {ptype: "off_t", pname: "offset"}, {ptype: "off_t", pname: "len"}, {ptype: "const char*", pname: "pathname"}],
		"timerfd_settime":      [{ptype: "int", pname: "fd"}, {ptype: "int", pname: "flags"}, {ptype: "const struct itimerspec*", pname: "new_value"}, {ptype: "struct itimerspec*", pname: "old_value"}],
		"timerfd_gettime":      [{ptype: "int", pname: "fd"}, {ptype: "struct itimerspec*", pname: "curr_value"}],
		"accept4":             [{ptype: "int", pname: "sockfd"}, {ptype: "struct sockaddr*", pname: "addr"}, {ptype: "int*", pname: "addrlen"}, {ptype: "int", pname: "flags"}],
		"signalfd4":           [{ptype: "int", pname: "fd"}, {ptype: "const sigset_t*", pname: "mask"}, {ptype: "size_t", pname: "sizemask"}, {ptype: "int", pname: "flags"}],
		"eventfd2":            [{ptype: "unsigned int", pname: "initval"}, {ptype: "int", pname: "flags"}],
		"epoll_create1":        [{ptype: "int", pname: "flags"}],
		"dup3":                [{ptype: "int", pname: "oldfd"}, {ptype: "int", pname: "newfd"}, {ptype: "int", pname: "flags"}],
		"pipe2":               [{ptype: "int*", pname: "pipefd"}, {ptype: "int", pname: "flags"}],
		"inotifyinit1":        [{ptype: "int", pname: "flags"}],
		"preadv":              [{ptype: "int", pname: "fd"}, {ptype: "const struct iovec*", pname: "iov"}, {ptype: "unsigned long", pname: "iovcnt"}, {ptype: "unsigned long", pname: "pos_l"}, {ptype: "unsigned long", pname: "pos_h"}],
		"pwritev":             [{ptype: "int", pname: "fd"}, {ptype: "const struct iovec*", pname: "iov"}, {ptype: "unsigned long", pname: "iovcnt"}, {ptype: "unsigned long", pname: "pos_l"}, {ptype: "unsigned long", pname: "pos_h"}],
		"rttgsigqueueinfo":    [{ptype: "pid_t", pname: "tgid"}, {ptype: "pid_t", pname: "tid"}, {ptype: "int", pname: "sig"}, {ptype: "siginfo_t*", pname: "info"}],
		"perfeventopen":       [{ptype: "struct perf_event_attr*", pname: "attr"}, {ptype: "pid_t", pname: "pid"}, {ptype: "int", pname: "cpu"}, {ptype: "int", pname: "group_fd"}, {ptype: "unsigned long", pname: "flags"}],
		"recvmmsg":            [{ptype: "int", pname: "sockfd"}, {ptype: "struct mmsghdr*", pname: "msgvec"}, {ptype: "unsigned int", pname: "vlen"}, {ptype: "int", pname: "flags"}, {ptype: "struct timespec*", pname: "timeout"}],
		"fanotifyinit":        [{ptype: "unsigned int", pname: "flags"}, {ptype: "unsigned int", pname: "event_f_flags"}],
		"fanotifymark":        [{ptype: "int", pname: "fanotify_fd"}, {ptype: "unsigned int", pname: "flags"}, {ptype: "u64", pname: "mask"}, {ptype: "int", pname: "dirfd"}, {ptype: "const char*", pname: "pathname"}],
		"prlimit64":           [{ptype: "pid_t", pname: "pid"}, {ptype: "int", pname: "resource"}, {ptype: "const struct rlimit64*", pname: "new_limit"}, {ptype: "struct rlimit64*", pname: "old_limit"}],
		"nametohandleat":      [{ptype: "int", pname: "dirfd"}, {ptype: "const char*", pname: "pathname"}, {ptype: "struct file_handle*", pname: "handle"}, {ptype: "int*", pname: "mount_id"}, {ptype: "int", pname: "flags"}],
		"openbyhandleat":      [{ptype: "int", pname: "mount_fd"}, {ptype: "struct file_handle*", pname: "handle"}, {ptype: "int", pname: "flags"}],
		"clockadjtime":        [{ptype: "const clockid_t", pname: "clk_id"}, {ptype: "struct timex*", pname: "buf"}],
		"syncfs":              [{ptype: "int", pname: "fd"}],
		"sendmmsg":            [{ptype: "int", pname: "sockfd"}, {ptype: "struct mmsghdr*", pname: "msgvec"}, {ptype: "unsigned int", pname: "vlen"}, {ptype: "int", pname: "flags"}],
		"setns":               [{ptype: "int", pname: "fd"}, {ptype: "int", pname: "nstype"}],
		"getcpu":              [{ptype: "unsigned int*", pname: "cpu"}, {ptype: "unsigned int*", pname: "node"}, {ptype: "struct getcpu_cache*", pname: "tcache"}],
		"processvmreadv":      [{ptype: "pid_t", pname: "pid"}, {ptype: "const struct iovec*", pname: "local_iov"}, {ptype: "unsigned long", pname: "liovcnt"}, {ptype: "const struct iovec*", pname: "remote_iov"}, {ptype: "unsigned long", pname: "riovcnt"}, {ptype: "unsigned long", pname: "flags"}],
		"processvmwritev":     [{ptype: "pid_t", pname: "pid"}, {ptype: "const struct iovec*", pname: "local_iov"}, {ptype: "unsigned long", pname: "liovcnt"}, {ptype: "const struct iovec*", pname: "remote_iov"}, {ptype: "unsigned long", pname: "riovcnt"}, {ptype: "unsigned long", pname: "flags"}],
		"kcmp":                [{ptype: "pid_t", pname: "pid1"}, {ptype: "pid_t", pname: "pid2"}, {ptype: "int", pname: "type"}, {ptype: "unsigned long", pname: "idx1"}, {ptype: "unsigned long", pname: "idx2"}],
		"finitmodule":         [{ptype: "int", pname: "fd"}, {ptype: "const char*", pname: "param_values"}, {ptype: "int", pname: "flags"}],
		"schedsetattr":        [{ptype: "pid_t", pname: "pid"}, {ptype: "struct sched_attr*", pname: "attr"}, {ptype: "unsigned int", pname: "flags"}],
		"schedgetattr":        [{ptype: "pid_t", pname: "pid"}, {ptype: "struct sched_attr*", pname: "attr"}, {ptype: "unsigned int", pname: "size"}, {ptype: "unsigned int", pname: "flags"}],
		"renameat2":           [{ptype: "int", pname: "olddirfd"}, {ptype: "const char*", pname: "oldpath"}, {ptype: "int", pname: "newdirfd"}, {ptype: "const char*", pname: "newpath"}, {ptype: "unsigned int", pname: "flags"}],
		"seccomp":             [{ptype: "unsigned int", pname: "operation"}, {ptype: "unsigned int", pname: "flags"}, {ptype: "const void*", pname: "args"}],
		"getrandom":           [{ptype: "void*", pname: "buf"}, {ptype: "size_t", pname: "buflen"}, {ptype: "unsigned int", pname: "flags"}],
		"memfdcreate":         [{ptype: "const char*", pname: "name"}, {ptype: "unsigned int", pname: "flags"}],
		"kexecfileload":       [{ptype: "int", pname: "kernel_fd"}, {ptype: "int", pname: "initrd_fd"}, {ptype: "unsigned long", pname: "cmdline_len"}, {ptype: "const char*", pname: "cmdline"}, {ptype: "unsigned long", pname: "flags"}],
		"bpf":                 [{ptype: "int", pname: "cmd"}, {ptype: "union bpf_attr*", pname: "attr"}, {ptype: "unsigned int", pname: "size"}],
		"execveat":            [{ptype: "int", pname: "dirfd"}, {ptype: "const char*", pname: "pathname"}, {ptype: "const char*const*", pname: "argv"}, {ptype: "const char*const*", pname: "envp"}, {ptype: "int", pname: "flags"}],
		"userfaultfd":         [{ptype: "int", pname: "flags"}],
		"membarrier":          [{ptype: "int", pname: "cmd"}, {ptype: "int", pname: "flags"}],
		"mlock2":              [{ptype: "const void*", pname: "addr"}, {ptype: "size_t", pname: "len"}, {ptype: "int", pname: "flags"}],
		"copyfilerange":       [{ptype: "int", pname: "fd_in"}, {ptype: "off_t*", pname: "off_in"}, {ptype: "int", pname: "fd_out"}, {ptype: "off_t*", pname: "off_out"}, {ptype: "size_t", pname: "len"}, {ptype: "unsigned int", pname: "flags"}],
		"preadv2":             [{ptype: "int", pname: "fd"}, {ptype: "const struct iovec*", pname: "iov"}, {ptype: "unsigned long", pname: "iovcnt"}, {ptype: "unsigned long", pname: "pos_l"}, {ptype: "unsigned long", pname: "pos_h"}, {ptype: "int", pname: "flags"}],
		"pwritev2":            [{ptype: "int", pname: "fd"}, {ptype: "const struct iovec*", pname: "iov"}, {ptype: "unsigned long", pname: "iovcnt"}, {ptype: "unsigned long", pname: "pos_l"}, {ptype: "unsigned long", pname: "pos_h"}, {ptype: "int", pname: "flags"}],
		"pkeymprotect":        [{ptype: "void*", pname: "addr"}, {ptype: "size_t", pname: "len"}, {ptype: "int", pname: "prot"}, {ptype: "int", pname: "pkey"}],
		"pkeyalloc":           [{ptype: "unsigned int", pname: "flags"}, {ptype: "unsigned long", pname: "access_rights"}],
		"pkeyfree":            [{ptype: "int", pname: "pkey"}],
		"statx":               [{ptype: "int", pname: "dirfd"}, {ptype: "const char*", pname: "pathname"}, {ptype: "int", pname: "flags"}, {ptype: "unsigned int", pname: "mask"}, {ptype: "struct statx*", pname: "statxbuf"}],
	}
)

import sys
target = sys.argv[1]

type_format = "num+type+name+comment"

if len(sys.argv) == 3:
    type_format = sys.argv[2]

config = {
    "num": False, 
    "type": False, 
    "name": False, 
    "comment": False 
}

formats = type_format.split('+')
for f in formats:
    config[f] = True

# formats = type_format.split('+')
# for i in range(len(formats)):
#     config[formats[i]] = i

syscall = syscalls[target]

def find_syscall_num(target):
    num = 0
    for key in syscalls:
        if key != target:
            num=num+1
        else:
            break
    return num
    
s = ""

if config['num']:
    s += f'{find_syscall_num(target):<4}: '

s += '['
for args in syscall:
    for f in formats:
        if f == 'type' and config[f]:
            s += f'{args[ptype]}'
        if f == 'name' and config[f]:
            s += f'"{args[pname]}"'

    if syscall[-1] == args:
        break
    s += f','

s += ']'

if config['comment']:
    s += f"{'# '+target:>50}"

print(s)