version: "3.7"

services:
  memcached:
    image: memcached:1.5.22
    restart: unless-stopped
    network_mode: host
    container_name: memcached

  mongo:
    image: mongo:3.6.8
    restart: unless-stopped
    network_mode: host
    container_name: mongo

  redis:
    image: redis:5.0.7
    restart: unless-stopped
    network_mode: host
    container_name: redis