import os
import subprocess
import time
import sys
import json
import threading
from socket import *
from pymongo import MongoClient

syscall_category = {
    "read" : "fs",
    "write" : "fs",
    "open" : "fs",
    "close" : "fs",
    "stat" : "fs",
    "fstat" : "fs",
    "lstat" : "fs",
    "poll" : "fs",
    "lseek" : "fs",
    "mmap" : "arch",
    "mprotect" : "mm",
    "munmap" : "mm",
    "brk" : "mm",
    "rt_sigaction" : "kernel",
    "rt_sigprocmask" : "kernel",
    "rt_sigreturn" : "arch",
    "ioctl" : "fs",
    "pread64" : "fs",
    "pwrite64" : "fs",
    "readv" : "fs",
    "writev" : "fs",
    "access" : "fs",
    "pipe" : "fs",
    "select" : "fs",
    "sched_yield" : "kernel",
    "mremap" : "mm",
    "msync" : "mm",
    "mincore" : "mm",
    "madvise" : "mm",
    "shmget" : "ipc",
    "shmat" : "ipc",
    "shmctl" : "ipc",
    "dup" : "fs",
    "dup2" : "fs",
    "pause" : "kernel",
    "nanosleep" : "kernel",
    "getitimer" : "kernel",
    "alarm" : "kernel",
    "setitimer" : "kernel",
    "getpid" : "kernel",
    "sendfile64" : "fs",
    "socket" : "net",
    "connect" : "net",
    "accept" : "net",
    "sendto" : "net",
    "recvfrom" : "net",
    "sendmsg" : "net",
    "recvmsg" : "net",
    "shutdown" : "net",
    "bind" : "net",
    "listen" : "net",
    "getsockname" : "net",
    "getpeername" : "net",
    "socketpair" : "net",
    "setsockopt" : "net",
    "getsockopt" : "net",
    "clone" : "kernel",
    "fork" : "kernel",
    "vfork" : "kernel",
    "execve" : "fs",
    "exit" : "kernel",
    "wait4" : "kernel",
    "kill" : "kernel",
    "uname" : "kernel",
    "semget" : "ipc",
    "semop" : "ipc",
    "semctl" : "ipc",
    "shmdt" : "ipc",
    "msgget" : "ipc",
    "msgsnd" : "ipc",
    "msgrcv" : "ipc",
    "msgctl" : "ipc",
    "fcntl" : "fs",
    "flock" : "fs",
    "fsync" : "fs",
    "fdatasync" : "fs",
    "truncate" : "fs",
    "ftruncate" : "fs",
    "getdents" : "fs",
    "getcwd" : "fs",
    "chdir" : "fs",
    "fchdir" : "fs",
    "rename" : "fs",
    "mkdir" : "fs",
    "rmdir" : "fs",
    "creat" : "fs",
    "link" : "fs",
    "unlink" : "fs",
    "symlink" : "fs",
    "readlink" : "fs",
    "chmod" : "fs",
    "fchmod" : "fs",
    "chown" : "fs",
    "fchown" : "fs",
    "lchown" : "fs",
    "umask" : "kernel",
    "gettimeofday" : "kernel",
    "getrlimit" : "kernel",
    "getrusage" : "kernel",
    "sysinfo" : "kernel",
    "times" : "kernel",
    "ptrace" : "kernel",
    "getuid" : "kernel",
    "syslog" : "kernel",
    "getgid" : "kernel",
    "setuid" : "kernel",
    "setgid" : "kernel",
    "geteuid" : "kernel",
    "getegid" : "kernel",
    "setpgid" : "kernel",
    "getppid" : "kernel",
    "getpgrp" : "kernel",
    "setsid" : "kernel",
    "setreuid" : "kernel",
    "setregid" : "kernel",
    "getgroups" : "kernel",
    "setgroups" : "kernel",
    "setresuid" : "kernel",
    "getresuid" : "kernel",
    "setresgid" : "kernel",
    "getresgid" : "kernel",
    "getpgid" : "kernel",
    "setfsuid" : "kernel",
    "setfsgid" : "kernel",
    "getsid" : "kernel",
    "capget" : "kernel",
    "capset" : "kernel",
    "rt_sigpending" : "kernel",
    "rt_sigtimedwait" : "kernel",
    "rt_sigqueueinfo" : "kernel",
    "rt_sigsuspend" : "kernel",
    "sigaltstack" : "kernel",
    "utime" : "fs",
    "mknod" : "fs",
    "personality" : "kernel",
    "ustat" : "fs",
    "statfs" : "fs",
    "fstatfs" : "fs",
    "sysfs" : "fs",
    "getpriority" : "kernel",
    "setpriority" : "kernel",
    "sched_setparam" : "kernel",
    "sched_getparam" : "kernel",
    "sched_setscheduler" : "kernel",
    "sched_getscheduler" : "kernel",
    "sched_get_priority_max" : "kernel",
    "sched_get_priority_min" : "kernel",
    "sched_rr_get_interval" : "kernel",
    "mlock" : "mm",
    "munlock" : "mm",
    "mlockall" : "mm",
    "munlockall" : "mm",
    "vhangup" : "fs",
    "modify_ldt" : "arch",
    "pivot_root" : "fs",
    "sysctl" : "kernel",
    "prctl" : "kernel",
    "arch_prctl" : "arch",
    "adjtimex" : "kernel",
    "setrlimit" : "kernel",
    "chroot" : "fs",
    "sync" : "fs",
    "acct" : "kernel",
    "settimeofday" : "kernel",
    "mount" : "fs",
    "umount" : "fs",
    "swapon" : "mm",
    "swapoff" : "mm",
    "reboot" : "kernel",
    "sethostname" : "kernel",
    "setdomainname" : "kernel",
    "iopl" : "arch",
    "ioperm" : "arch",
    "init_module" : "kernel",
    "delete_module" : "kernel",
    "quotactl" : "fs",
    "gettid" : "kernel",
    "readahead" : "mm",
    "setxattr" : "fs",
    "lsetxattr" : "fs",
    "fsetxattr" : "fs",
    "getxattr" : "fs",
    "lgetxattr" : "fs",
    "fgetxattr" : "fs",
    "listxattr" : "fs",
    "llistxattr" : "fs",
    "flistxattr" : "fs",
    "removexattr" : "fs",
    "lremovexattr" : "fs",
    "fremovexattr" : "fs",
    "tkill" : "kernel",
    "time" : "kernel",
    "futex" : "kernel",
    "sched_setaffinity" : "kernel",
    "sched_getaffinity" : "kernel",
    "io_setup" : "fs",
    "io_destroy" : "fs",
    "io_getevents" : "fs",
    "io_submit" : "fs",
    "io_cancel" : "fs",
    "lookup_dcookie" : "fs",
    "epoll_create" : "fs",
    "remap_file_pages" : "mm",
    "getdents64" : "fs",
    "set_tid_address" : "kernel",
    "restart_syscall" : "kernel",
    "semtimedop" : "ipc",
    "fadvise64" : "mm",
    "timer_create" : "kernel",
    "timer_settime" : "kernel",
    "timer_gettime" : "kernel",
    "timer_getoverrun" : "kernel",
    "timer_delete" : "kernel",
    "clock_settime" : "kernel",
    "clock_gettime" : "kernel",
    "clock_getres" : "kernel",
    "clock_nanosleep" : "kernel",
    "exit_group" : "kernel",
    "epoll_wait" : "fs",
    "epoll_ctl" : "fs",
    "tgkill" : "kernel",
    "utimes" : "fs",
    "mbind" : "mm",
    "set_mempolicy" : "mm",
    "get_mempolicy" : "mm",
    "mq_open" : "ipc",
    "mq_unlink" : "ipc",
    "mq_timedsend" : "ipc",
    "mq_timedreceive" : "ipc",
    "mq_notify" : "ipc",
    "mq_getsetattr" : "ipc",
    "kexec_load" : "kernel",
    "waitid" : "kernel",
    "add_key" : "security",
    "request_key" : "security",
    "keyctl" : "security",
    "ioprio_set" : "fs",
    "ioprio_get" : "fs",
    "inotify_init" : "fs",
    "inotify_add_watch" : "fs",
    "inotify_rm_watch" : "fs",
    "migrate_pages" : "mm",
    "openat" : "fs",
    "mkdirat" : "fs",
    "mknodat" : "fs",
    "fchownat" : "fs",
    "futimesat" : "fs",
    "newfstatat" : "fs",
    "unlinkat" : "fs",
    "renameat" : "fs",
    "linkat" : "fs",
    "symlinkat" : "fs",
    "readlinkat" : "fs",
    "fchmodat" : "fs",
    "faccessat" : "fs",
    "pselect6" : "fs",
    "ppoll" : "fs",
    "unshare" : "kernel",
    "set_robust_list" : "kernel",
    "get_robust_list" : "kernel",
    "splice" : "fs",
    "tee" : "fs",
    "sync_file_range" : "fs",
    "vmsplice" : "fs",
    "move_pages" : "mm",
    "utimensat" : "fs",
    "epoll_pwait" : "fs",
    "signalfd" : "fs",
    "timerfd_create" : "fs",
    "eventfd" : "fs",
    "fallocate" : "fs",
    "timerfd_settime" : "fs",
    "timerfd_gettime" : "fs",
    "accept4" : "net",
    "signalfd4" : "fs",
    "eventfd2" : "fs",
    "epoll_create1" : "fs",
    "dup3" : "fs",
    "pipe2" : "fs",
    "inotify_init1" : "fs",
    "preadv" : "fs",
    "pwritev" : "fs",
    "rt_tgsigqueueinfo" : "kernel",
    "perf_event_open" : "kernel",
    "recvmmsg" : "net",
    "fanotify_init" : "fs",
    "fanotify_mark" : "fs",
    "prlimit64" : "kernel",
    "name_to_handle_at" : "fs",
    "open_by_handle_at" : "fs",
    "clock_adjtime" : "kernel",
    "syncfs" : "fs",
    "sendmmsg" : "net",
    "setns" : "kernel",
    "getcpu" : "kernel",
    "process_vm_readv" : "mm",
    "process_vm_writev" : "mm",
    "kcmp" : "kernel",
    "finit_module" : "kernel"
}

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Error! put COLLECTOR_DB TARGET")
        exit()

    client = MongoClient("mongodb://XXXXX:XXXXXXXX@XXX.XXX.XXX.XXX:XXXXX/admin")
    db = client[sys.argv[1]]
    colList = sorted([collection for collection in db.list_collection_names()])
    print("ITERATION,DB,workload,record_count,record_size,operation,client,tid,syscall,type,count")
    for collection in colList:
        col = db[collection]
        if sys.argv[2] != "all" and sys.argv[2] not in collection:
            continue
        doc_count = col.count_documents({})
        pipeline = [
            {
                "$group": 
                    {
                        "_id": {"threadId": "$threadId", "eventName":"$eventName"},
                        "count": {"$sum": 1}
                    }
            }
        ]
        res = col.aggregate(pipeline)
        
        split_str = collection.split("_")
        for row in res:
            category = ""
            if row["_id"]["eventName"] not in syscall_category:
                category = "etc"
            else:
                category = syscall_category[row["_id"]["eventName"]]
            
            dbname = split_str[0]
            workload = split_str[1]
            record_count = split_str[2]
            record_size = split_str[3]
            numclient = split_str[4]
            operations = split_str[5]
            iteration = split_str[-1]
            tid=row["_id"]["threadId"]
            syscall=row["_id"]["eventName"]
            # type=category
            count=row["count"]

            print(f"{iteration},{dbname},{workload},{record_count},{record_size},{operations},{numclient},{tid},{syscall},{category},{count}")
